### ISSUE TITLE
IONOS (formerly 1&1Hosting) Failed to connect to server: Connection timed out (110) SMTP connect() failed

### ISSUE THREAD

**Issue by bonnevillessei** [getgrav/grav-plugin-email#111]
Found a hosting restriction when using the Email plugin on IONOS (formerly 1&1 Hosting). IONOS does not allow using an external smtp server such as Google gmail, even with different ports/encryptions.

This was confirmed when I called IONOS. You can use the their smtp servers with these settings.

Mail Engine = smtp
Mail Server = smtp.ionos.com
Port = 25
Encrytption = none
Email = youremailhostedbyionos
Password = yourpassword

Hope this helps others.

**Comment by LouLeGrain** [comment]
Very helpful, i had trouble with ionos's SMTP, thx alot !
TLS encryption worked for me : 
```
mailer:
  engine: smtp
  smtp:
    server: smtp.ionos.com
    port: 25
    encryption: tls
    user: 'mail@mydomain.fr'
    password: 'mygreatpasswd'
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
```
