### ISSUE TITLE
Messages come without attachments

### ISSUE THREAD

**Issue by k1ll1n** [getgrav/grav-plugin-email#115]
I did the following - actions!
Installed Grav from Github 
Installed email plugin from Github
Installed forms plugin from Github

I included the form to the template Quark
`{% include 'forms/form.html.twig' %}`

My blueprint
```yaml
forms:
    feedback_form:
        method: POST
        fields:
            -
                name: name
                type: text
                validate:
                    required: true
            -
                name: tel
                type: text
                validate:
                    required: true
            -
                name: email
                type: text
                validate:
                    rule: email
                    required: true
            -   
                name: brief
                type: file
                multiple: false
                destination: 'user/data/files'
                accept: 
                    - '*'
        buttons:
            -
               type: submit
               value: 'Оставить заявку'
               classes: submit
        process:
            -
               email:
                   from: '{{ config.plugins.email.from }}'
                   to:
                       - '{{ config.plugins.email.to }}'
                   subject: '[Feedback] {{ form.value.name|e }}'
                   body: '{% include ''forms/data.html.twig'' %}'
                   attachments:
                       - 'brief'
            -
               save:
                   fileprefix: feedback-
                   dateformat: Ymd-His-u
                   extension: txt
                   body: '{% include ''forms/data.txt.twig'' %}' 
```
My Settings for Email Plugin
```yaml
enabled: true
from: dev-user@3832456.ru
from_name: 'Dev User'
to: subikrus@gmail.com
to_name: Alex
queue:
  enabled: false
  flush_frequency: '* * * * *'
  flush_msg_limit: 10
  flush_time_limit: 100
mailer:
  engine: smtp
  smtp:
    server: smtp.yandex.ru
    port: 465
    encryption: ssl
    user: login@domain.ru
    password: password
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: true
```
But messages still come without attachments
As well as grav does not create a folder for `attachments user/data/files`

Grav v1.6.9
Email  v3.0.2
Form  v3.0.3
