### ISSUE TITLE
GMail authenication

### ISSUE THREAD

**Issue by KDeverell** [getgrav/grav-plugin-email#118]
I have tried to configure the plugin to use Gmail and I am getting this response:

`Expected response code 235 but got code "534"`

I have tried the configuring the email plugin with both SSL and TLS, as per docs and other tickets on this forum. I have also enabled unsecure email option in my account. The strange is if I use an email address that is hosted through gmail using a custom domain it works, but if I use my email account xxxx@gmail.com it doesn't work. I have test a couple of different xxxx@gmail.com and they all through the same error. My settings are:

```
mailer:
  engine: smtp
  smtp:
    server: smtp.gmail.com
    port: 465
    encryption: ssl
    user: 'YOUR_GOOGLE_EMAIL_ADDRESS'
    password: 'YOUR_GOOGLE_PASSWORD'

```
Any help most welcome!
Thanks K.
