### ISSUE TITLE
php7.3 Connection smtp error;

### ISSUE THREAD

**Issue by coldestheart** [getgrav/grav-plugin-email#123]
Using docker container with php7.3

**Here page:**

```
process:
    twig: true
cache_enable: false
form:
    name: contact
    fields:
        name:
          label: Name
          placeholder: Enter your name
          autocomplete: on
          type: text
          validate:
            required: true

        email:
          label: Email
          placeholder: Enter your email address
          type: email
          validate:
            required: true

        message:
          label: Message
          placeholder: Enter your message
          type: textarea
          validate:
            required: true

    buttons:
        submit:
          type: submit
          value: Submit
        reset:
          type: reset
          value: Reset

    process:
        save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        email:
            from: "{{ config.plugins.email.from }}"
            to: "{{ config.plugins.email.to }}"
            subject: "[Site Contact Form] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
        message: Will be in touch`
```

Here plugin config file:
```

enabled: true
from: buhgalterkursk@gmail.com
from_name: 'Buhgalter'
to: buhgalterkursk@gmail.com
queue:
  enabled: false
  flush_frequency: '* * * * *'
  flush_msg_limit: 10
  flush_time_limit: 100
mailer:
  engine: smtp
  smtp:
    server: smtp.gmail.com
    port: 587
    encryption: tls
    user: buhgalterkursk@gmail.com
    password: ******
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: true

```

always getting error

> 
Connection could not be established with host smtp.gmail.com [Connection timed out #110] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.gmail.com [Connection timed out #110] (code: 0)

also this error with any other mail provider like yandex or mailru

More details: 

```
Files empty 
Cookies
_ym_uid
"1572003906460599356"
_ym_d
"1572003906"
pagekit_auth
"FxZKQCW0DkhU2l1sb.oOzBFLBFsM2eaeWDs8Xk51uMFCaHRWKih9b4oLphq9j7mQ"
grav-tabs-state
"{"tab-content.options.advanced":"data.advanced","tab-content.options.advanced.holaSetings":"data.advanced","tab-content.options.advanced.blog":"data.advanced"," ▶"
buhgalter-kursk-40d1b2d
"0ff96e1948c4f6005a0f423d409e0d37"
buhgalter-kursk-40d1b2d-admin
"bd293d749929a31df036ab48c8070792"
Session
redirect_after_login
"/kontakty"
user
User {#109}
unique_form_id
"wsko7jgx254dh3bqaekn"
Server/Request Data
REDIRECT_STATUS
"200"
HTTP_HOST
"test.buhgalterkursk.ru"
HTTP_CONNECTION
"close"
HTTP_X_REAL_IP
"37.188.9.190"
HTTP_X_FORWARDED_FOR
"37.188.9.190"
HTTP_X_FORWARDED_PROTO
"https"
HTTP_X_FORWARDED_SSL
"on"
HTTP_X_FORWARDED_PORT
"443"
CONTENT_LENGTH
"197"
HTTP_USER_AGENT
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:70.0) Gecko/20100101 Firefox/70.0"
HTTP_ACCEPT
"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_LANGUAGE
"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3"
HTTP_ACCEPT_ENCODING
"gzip, deflate, br"
HTTP_REFERER
"https://test.buhgalterkursk.ru/ru/kontakty"
CONTENT_TYPE
"application/x-www-form-urlencoded"
HTTP_ORIGIN
"https://test.buhgalterkursk.ru"
HTTP_UPGRADE_INSECURE_REQUESTS
"1"
HTTP_CACHE_CONTROL
"max-age=0"
HTTP_COOKIE
"_ym_uid=1572003906460599356; _ym_d=1572003906; pagekit_auth=FxZKQCW0DkhU2l1sb.oOzBFLBFsM2eaeWDs8Xk51uMFCaHRWKih9b4oLphq9j7mQ; grav-tabs-state={%22tab-content.op ▶"
PATH
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
SERVER_SIGNATURE
"<address>Apache/2.4.38 (Debian) Server at test.buhgalterkursk.ru Port 80</address>
"
SERVER_SOFTWARE
"Apache/2.4.38 (Debian)"
SERVER_NAME
"test.buhgalterkursk.ru"
SERVER_ADDR
"172.18.0.3"
SERVER_PORT
"80"
REMOTE_ADDR
"172.18.0.2"
DOCUMENT_ROOT
"/var/www/html"
REQUEST_SCHEME
"http"
CONTEXT_PREFIX
""
CONTEXT_DOCUMENT_ROOT
"/var/www/html"
SERVER_ADMIN
"webmaster@localhost"
SCRIPT_FILENAME
"/var/www/html/index.php"
REMOTE_PORT
"49078"
REDIRECT_URL
"/ru/kontakty"
GATEWAY_INTERFACE
"CGI/1.1"
SERVER_PROTOCOL
"HTTP/1.1"
REQUEST_METHOD
"POST"
QUERY_STRING
""
REQUEST_URI
"/ru/kontakty"
SCRIPT_NAME
"/index.php"
PHP_SELF
"/index.php"
REQUEST_TIME_FLOAT
1574434590.316
REQUEST_TIME
1574434590
argv
[]
argc
0
Environment Variables
HOSTNAME
"56528965959b"
VIRTUAL_PROTO
"http"
PHP_VERSION
"7.3.11"
APACHE_CONFDIR
"/etc/apache2"
PHP_MD5
""
LETSENCRYPT_HOST
"test.buhgalterkursk.ru"
PHP_INI_DIR
"/usr/local/etc/php"
GPG_KEYS
"CBAF69F173A0FEA4B537F470D66C9593118BCCB6 F38252826ACD957EF380D39F2F7956BC5DA04B5D"
PHP_LDFLAGS
"-Wl,-O1 -Wl,--hash-style=both -pie"
PWD
"/var/www"
APACHE_LOG_DIR
"/var/log/apache2"
LANG
"C"
PHP_SHA256
"657cf6464bac28e9490c59c07a2cf7bb76c200f09cfadf6e44ea64e95fa01021"
APACHE_PID_FILE
"/var/run/apache2/apache2.pid"
VIRTUAL_PORT
"80"
PHPIZE_DEPS
"autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c"
LETSENCRYPT_EMAIL
"support@it-tehcon.ru"
VIRTUAL_HOST
"test.buhgalterkursk.ru"
PHP_URL
"https://www.php.net/get/php-7.3.11.tar.xz/from/this/mirror"
APACHE_RUN_GROUP
"www-data"
APACHE_LOCK_DIR
"/var/lock/apache2"
PHP_EXTRA_CONFIGURE_ARGS
"--with-apxs2 --disable-cgi"
SHLVL
"0"
PHP_CFLAGS
"-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
APACHE_RUN_DIR
"/var/run/apache2"
APACHE_ENVVARS
"/etc/apache2/envvars"
APACHE_RUN_USER
"www-data"
PATH
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PHP_EXTRA_BUILD_DEPS
"apache2-dev"
PHP_ASC_URL
"https://www.php.net/get/php-7.3.11.tar.xz.asc/from/this/mirror"
PHP_CPPFLAGS
"-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
GRAV_VERSION
"1.6.16"
Registered Handlers
0. Whoops\Handler\CallbackHandler 
1. Whoops\Handler\PrettyPageHandler
```
