### ISSUE TITLE
Nginx hangs when submitting contact form

### ISSUE THREAD

**Issue by makruiten** [getgrav/grav-plugin-email#14]
I'm getting a 503 gateway timeout, but the mail sends correctly. My guess is that my vps is a bit slow with sending mail over smtp and Grav waits for it to succeed before showing the 'Thank you' message. Is there any way to stop CeeVee from waiting until the email is sent?

**Comment by flaviocopes** [comment]
Does it happen only with SMTP or also with PHP Mail or Sendmail?

**Comment by makruiten** [comment]
This issue was meant for the CeeVee skeleton, that's why I posted the specifics above, but it might as well be an issue with your plugin. I'll do some tests after dinner (CET here).

**Comment by makruiten** [comment]
Now it's not sending mail altogether and to be honest I don't know where to start debugging. Non of the options do anything and the page refreshes instantly. It's getting late here, so I'll take a look again tomorrow.

**Comment by flaviocopes** [comment]
It should work fine. Just tested with Nginx too, that is not the issue.

Setup an account with https://mailtrap.io and instruct the email plugin to use it, for example your user/config/plugins/email.yaml should be

```
mailer:
  engine: smtp
  smtp:
    server: mailtrap.io
    port: 2525
    encryption: none
    user: YOUR_MAILTRAP_INBOX_USER
    password: YOUR_MAILTRAP_INBOX_PASSWORD
```

Check if the emails arrive there.
