### ISSUE TITLE
Undefined variable: errno

### ISSUE THREAD

**Issue by ferino75** [getgrav/grav-plugin-email#144]
Hello, I cannot send email
Swift_TransportException
Connection could not be established with host smtp.gmail.com :Undefined variable: errno

/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php

Grav v1.7.5

```yaml
 enabled: true
 from: info@experts4seo.sk
 from_name: E4S
 to: aaa@gmail.com
 to_name: null
 queue:
   enabled: false
   flush_frequency: '* * * * *'
   flush_msg_limit: 10
   flush_time_limit: 100
 mailer:
   engine: smtp
   smtp:
     server: smtp.gmail.com
     port: 587
     encryption: tls
     user: xxx@gmail.com
     password: xxx
     auth_mode: null
   sendmail:
     bin: '/usr/sbin/sendmail -bs'
 content_type: text/html
 debug: true
 charset: null
 cc: null
 cc_name: null
 bcc: null
 reply_to: null
 reply_to_name: null
 body: null
```

What is _errno_, pls?
