### ISSUE TITLE
Failed to authenticate on SMTP server with username "apikey" using 2 possible authenticators

### ISSUE THREAD

**Issue by AndrewNB** [getgrav/grav-plugin-email#149]
Hi,

I have the following error when trying to send an email.  Running locally I have no issues but on an Azure webapp I get the following error:

0 - Failed to authenticate on SMTP server with username "apikey" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got an empty response. Authenticator PLAIN returned Expected response code 250 but got an empty response.

My config is in email.yaml:
```
mailer:
  engine: smtp
  smtp:
    server: smtp.sendgrid.net
    port: 587
    encryption: tls
    user: apikey
    password: **************************************
  sendmail:
    bin: "/usr/sbin/sendmail -bs"
```

Local Env: Windows PHP V7.4.16
Azure Env: Windows PHP V7.4.11

Any idea what the issue is?  I would expect it to authenticate in the same way and it's not.
