### ISSUE TITLE
Issues with multiple recipients in recent versions (since 4.0 I believe)

### ISSUE THREAD

**Issue by rotanadan** [getgrav/grav-plugin-email#176]
If recipients in the headmatter use this format.

to:
    - testa@email.com
    - testb@email.com
    
It will only send to the first email as "testb@meail.com" <testa@email.com>

If you use this format

to:
    - Name <testa@email.com>
    - Nameb <testb@email.com>

multiple emails will work.

**Comment by rhukster** [comment]
Should be good for the next release.. Tested with this:

```
            to:
              -
                email: mail+3@example.com
                name: Joe Bloggs3
              - mail+4@example.com
              - Joe Bloggs5 <mail+5@example.com>
              - [mail+6@exmaple.com, Joe Bloggs6]
```
