### ISSUE TITLE
Spam issue when modifiying from

### ISSUE THREAD

**Issue by Kiouze** [getgrav/grav-plugin-email#177]
Hi! 

I've got a spam issue when i change the from parameter email by including the sender's email:

```
email:
  subject:  {{ form.value.name|e }}"
  body: "{% include 'forms/data.html.twig' %}"
  from: "{{ form.value.email|e }}"
```

If I don't include the sender email in this parameter, it will appear in the message body and the email won't go to spam BUT the sender will be the smtp adress I'm using, so when I click "Answer" in my email client I will answer to my smtp adress and not to the sender.

Is this some kind of email client spam regulation?

Thanks in advance for your answer.
