### ISSUE TITLE
"User is not set" error in recent versions

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-plugin-email#178]
I think this is only happening in versions 4+ since you switched to Symfony mailer.

Recent sites I've installed with this plugin have had intermittent problems where I see Grav logs like `2023-08-01 04:28:40 [CRITICAL] User is not set.` Does not seem to interfere with mail sending though, or site operation that I have noticed.

The main annoyance for me has been that it stops some CLI stuff working, particularly `bin/grav cache-clear`. Here is what I see there:

```shell
In AbstractTransportFactory.php line 46:                                                                                                                                
                                                                                                                                                                        
  User is not set.                                                                                                                                                      
                                                                                                                                                                        
                                                                                                                                                                        
cache [--invalidate] [--purge] [--all] [--assets-only] [--images-only] [--cache-only] [--tmp-only] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--env [ENV]] [--lang [LANG]] [--] <command>
```

This has been hard to isolate so please let me know if I can provide more information to help reproduce it.

The error message and `AbstractTransportFactory` have only been found in this plugin. I removed this plugin and the vendor one (sendinblue) to test this and the error went away. Reinstated the plugins and it came back.

The error is happening with at least two mail provider plugins: sendinblue and mailjet, so I don't think it's those plugins specifically. I'm using their APIs. Everything updated.

**Comment by rhukster** [comment]
What does your email config look like (please
redact sensitive information). 

Also can you provide an example form or scenario that exhibits this issue so I can try to recreate it. ?

**Comment by hughbris** [comment]
Thank you.

> Also can you provide an example form or scenario that exhibits this issue so I can try to recreate it. ?

There is no form exhibiting this behaviour. Mail is generated from a contact form successfully. Pretty textbook setup.

The error is only present in Grav logs and some CLI commands, at least `cache-clear` and I think other(s).

## Configs

### Site A

`email.yaml`:
```yaml
from: webserver@example.com
from_name: A website
to: info@example.com
to_name: Website A
reply_to: alt@example.com
reply_to_name: Website email alt
mailer:
  engine: mailjet
content_type: text/html
debug: true # it's a dev install
```

`email-mailjet.yaml`:
```yaml
enabled: true
transport: api
api_key: API_KEY_REDACTED
secret_key: SECRET_KEY_REDACTED
```

### Site B

`email.yaml`:
```yaml
from: website@example.com
from_name: "B website"
to: info@example.com
to_name: Website Owner
mailer:
  engine: sendinblue
content_type: text/html
debug: false # is an unlaunched prod site
```

`email-sendinblue.yaml`:
```yaml
enabled: true
transport: api
access_key: ACCESS_KEY_REDACTED
```
Let me know if I can provide anything else.
