### ISSUE TITLE
Email does not comply with addr-spec of RFC 2822

### ISSUE THREAD

**Issue by petrus9** [getgrav/grav-plugin-email#183]
When adding an  the following     Name Lastname <email@domain.com>  to the default "to" or "from"   I get the following error. 

Symfony \ Component \ Mime \ Exception \ RfcComplianceException
Email "Name lastname &lt;email@domain.com&gt;" does not comply with addr-spec of RFC 2822.  But as far as I am concerned it does comply. 

Here is my markdown for the contact form
[contact.md](https://github.com/getgrav/grav-plugin-email/files/15083634/contact.md)

**Comment by petrus9** [comment]
This is how it actually shows up in the error screen:

![image](https://github.com/getgrav/grav-plugin-email/assets/63444532/cbc041f1-70c9-4e91-90a7-72c82df95ab3)

**Comment by rhukster** [comment]
If this provided `contact.md` is using the same configuration file from you other issue, there was no value for `{{ config.plugins.email.from }}` nor `{{ config.plugins.email.to }}`.  These were both empty.  These need to be provided i a valid email format: https://github.com/getgrav/grav-plugin-email?tab=readme-ov-file#specifying-email-addresses

FYI, you should always include a `reply_to:` so when you receive an email from the contact form, you can click 'reply' and it will go to the user who entered the form data on your site. Something like:

```
reply_to: {mail:"{{ form.value.email }}", name:"{{ form.value.name|e }}"}
```

is the best solution assuming your form has a field for `email` and for `name`.

**Comment by petrus9** [comment]
Here is my new email.yaml

```
enabled: true
from: 'John Doe <john@johndoe.com>'
to: 'Jane Doe <jane@janedoe.com>'
mailer:
  engine: sendgrid
  smtp:
    server: localhost
    port: 25
    encryption: none
    user: null
    password: null
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: false
cc: null
bcc: null
reply_to: null
body: null
```

Which throws the RFC error 


Here is my contact.md  which I know does not have any lines for "name:"  not sure what I need to fix here so that emails are sent to  'Jane Doe <jane@janedoe.com>'  and come from 'John Doe <john@johndoe.com>'

```
title: Contact
heading: 'Say Hello.'
form:
    action: /home
    name: contact-form
    fields:
        -
            name: name
            label: Name
            placeholder: Name
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: Email
            type: email
            validate:
                required: true
        -
            name: message
            label: Message
            placeholder: Message
            type: textarea
            rows: 6
            validate:
                required: true
        -
            name: g-recaptcha-response
            label: Captcha
            type: captcha
            recaptcha_not_validated: 'Captcha not valid!'
    buttons:
        -
            type: submit
            value: 'Send Message'
    process:
        -
            captcha: true
            buttons: null
        -
            type: submit
            value: 'Send Message'
            process: null
        -
            email:
                from:
                    mail: '{{ config.plugins.email.from }}'
                to:
                    mail: '{{ config.plugins.email.to }}'
                reply_to:
                    mail: '{{ form.value.email }}'
                    name: '{{ form.value.name|e }}'
                subject: '[Contact] Message from {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: contact-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            display: thank-you
```

**Comment by rhukster** [comment]
OH, change your email `process: email:` section to:

```
-
            email:
                from: '{{ config.plugins.email.from }}'
                to: '{{ config.plugins.email.to }}'
                reply_to:
                    mail: '{{ form.value.email }}'
                    name: '{{ form.value.name|e }}'
                subject: '[Contact] Message from {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
```

You were setting the 'email' only part (`mail:`) with the combined email + name.  Just set `to:` and `from:` and you should be fine.

**Comment by petrus9** [comment]
when I change the `process: email: `section to your recommendation.  I get:

Symfony\Component\Mime\Exception\RfcComplianceException thrown with message "Email "Jane Doe &lt;jane@janedoe.com&gt;" does not comply with addr-spec of RFC 2822."

**Comment by rhukster** [comment]
So you have quotes around it? Try removing. May they are not regular quotes.

**Comment by petrus9** [comment]
> So you have quotes around it? Try removing. Maybe they are not regular quotes.

No quotes

**Comment by rhukster** [comment]
I’m at a loss 🤷‍♂️

works for me when I try.

**Comment by petrus9** [comment]
The way it shows up on my screen is like this:

![Screenshot 2024-04-24 153150](https://github.com/getgrav/grav-plugin-email/assets/63444532/9a252003-cc11-42d1-af78-cf1c359d85ce)

**Comment by rhukster** [comment]
Ya that’s weird. The escaping isn’t right.  But I don’t even know how you could do that from a yaml configuration.

**Comment by petrus9** [comment]
The only way I get it to work is if my email.yaml looks like this:
```
enabled: true
from: 'john@johndoe.com'
to: 'jane@janedoe.com'
mailer:
  engine: sendgrid
  smtp:
    server: localhost
    port: 25
    encryption: none
    user: null
    password: null
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: false
cc: null
bcc: null
reply_to: null
body: null
```

**Comment by petrus9** [comment]
@rhukster  so from what you wrote above when you name and email address to the Email plugin fields like so:


![Screenshot 2024-04-24 162040](https://github.com/getgrav/grav-plugin-email/assets/63444532/77db266e-c42e-499b-b939-6399526a9ff2)

Using:

```
email:
                from: '{{ config.plugins.email.from }}'
                to: '{{ config.plugins.email.to }}'
                reply_to:
                    mail: '{{ form.value.email }}'
                    name: '{{ form.value.name|e }}'
                subject: '[Contact] Message from {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'        

```

Your email is delivered coming from John Doe <john@johndoe.com>  and is sent to  Jane Doe ,<jane@janedoe.com> in full

in full `name-addr` format?

**Comment by Tredecate** [comment]
Just a heads up for anyone looking at this in the future, this exact issue was occurring for me when using the Landio theme's default form configuration. Here was the email plugin config I was using:

<details><summary><strong>Details</strong></summary>
<p>

```yml
enabled: true
from: 'Website <▬▬@▬▬▬▬.ca>'
to: ▬▬@▬▬▬▬.ca
mailer:
  engine: smtp
  smtp:
    server: smtp-relay.gmail.com
    port: 25
    encryption: tls
    user: ▬▬@▬▬▬▬.ca
    password: '▬'
  sendmail:
    bin: /usr/sbin/sendmail
content_type: text/plain
debug: false
cc: null
bcc: null
reply_to: ▬▬@▬▬▬▬.ca
body: null
```

</p>
</details> 

When trying to define an email address in the format `Firstname Lastname <name@domain.tld>`, the angle brackets were being escaped  to `&lt;` and `&gt;`

In the aforementioned form (defined in modular.md), the email process is defined as such:
```twig
email:
    from: '{{ config.plugins.email.from }}'
    to:
        - '{{ config.plugins.email.from }}'
    subject: '[Contact Request] {{ form.value.name|e }}'
    body: '{% include ''forms/data.html.twig'' %}'
``` 

It's great that it grabs the values from the plugin config, BUT... In this scenario, the Markdown content was being rendered as escaped HTML 🙂 

My solution was to add `|raw`, like so:
```twig
email:
    from: '{{ config.plugins.email.from|raw }}'
    to:
        - '{{ config.plugins.email.from|raw }}'
    subject: '[Contact Request] {{ form.value.name|e }}'
    body: '{% include ''forms/data.html.twig'' %}'
```
And it works! It should be noted that there _can_ be some degree of risk involved in passing through raw data, so maybe don't use this solution for user/public-input.
