### ISSUE TITLE
Gmail setup stopped working after the update

### ISSUE THREAD

**Issue by aspectvm** [getgrav/grav-plugin-email#185]
I had a setup for the gmail smtp, like so:

```yaml
debug: true
mailer:
  engine: smtp
  smtp:
    server: smtp.gmail.com
    port: 587
    user: 'emailName@gmail.com'
    password: 'xxxx xxxx xxxx xxxx'
```
 

It was working fine for my both sites (I have a multisite setup) until the most recent update to 4.1.0. version. Now, it is logging this error: 

> "Failed to authenticate on SMTP server with username "emailName@gmail.com" using the following authenticators: "LOGIN", "PLAIN", "XOAUTH2". Authenticator "LOGIN" returned "Expected response code "235" but got code "535", with message "535-5.7.8 Username and Password not accepted. For more information, go to 535 5.7.8  https://support.google.com/mail/?p=BadCredentials a640c23a62f3a-a6c805c59a2sm133747166b.50 - gsmtp".". Authenticator "PLAIN" returned "Expected response code "235" but got code "535", with message "535-5.7.8 Username and Password not accepted. For more information, go to 535 5.7.8  https://support.google.com/mail/?p=BadCredentials a640c23a62f3a-a6c805c59a2sm133747166b.50 - gsmtp".". Authenticator "XOAUTH2" returned "Expected response code "235" but got code "334", with message "334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==".".  [] []"

I have tested the same credentials with phpMailer in a separate script, and it works no problem. This plugin (for me, at least) only works with Outlook currently, but not with Gmail.
