### ISSUE TITLE
Emails are not getting sent

### ISSUE THREAD

**Issue by nem25** [getgrav/grav-plugin-email#38]
Hi, I have messaged a few times on gitter but since I didn't get a response there I thought to get in touch with the plugin creators directly.

I have installed the email and form plugin to create a contact form on my website.

Here is my user/config/plugins/email.yaml
```
enabled: true
from: <myemail>
from_name: Invite Request
to: <myemail>
to_name: <myname>
mailer: 
  engine: smtp
  smtp:
    server: smtp.mailgun.org
    encryption: none
    user: <mailgunusername>
    password: <mailgunpassword>
content_type: text/html
debug: true
```

And this is my form.md
```
---
title: Contact Form

form:
    name: signup

    fields:
        - name: name
          label: Name
          placeholder: Enter your name
          autofocus: on
          autocomplete: on
          tabindex: 1
          type: text
          validate:
            required: true

        - name: email
          label: Email
          placeholder: Enter your email address
          type: email
          tabindex: 2
          validate:
            required: true

        - name: message
          label: Message
          placeholder: Enter your message
          type: textarea
          tabindex: 3
          validate:
            required: false

    buttons:
        - type: submit
          value: Submit
          tabindex: 4
        - type: reset
          value: Reset
          tabindex: 5
    process:
        - email:
            subject: "[Invite Request] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.from }}"
              - "{{ form.value.email }}"
        - message: Thank you for getting in touch!
        - display: thankyou
---
```
And nothing seems to happen. There are no errors in the console. It's almost as if the plugin doesn't even get recognised.
