### ISSUE TITLE
could you precise how to 'make your modifications'

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav-plugin-email#5]
For instance, what are the possiblities about encryption (TLS?)
I mean: 'if I put my password there with no encryption then my password is send without protection?'
for server: localhost
this is a example when site is underconstruction?
Sorry not to be able to understand... Best regards...

**Comment by flaviocopes** [comment]
The Email plugin uses Swiftmailer. Swiftmailer supports encryption (http://swiftmailer.org/docs/sending.html#encrypted-smtp), you just need to add it to the `encryption` parameter of the configuration.

Example:

```
mailer:
  engine: smtp
  smtp:
    server: localhost
    port: 25
    encryption: 'tls'
```

**Comment by flaviocopes** [comment]
The Email plugin uses Swiftmailer. Swiftmailer supports encryption (http://swiftmailer.org/docs/sending.html#encrypted-smtp), you just need to add it to the `encryption` parameter of the configuration.

Example:

```
mailer:
  engine: smtp
  smtp:
    server: localhost
    port: 25
    encryption: 'tls'
```
