### ISSUE TITLE
No $params being send to email.php?

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-plugin-email#51]
I have a form configured to send email via SMTP:

my email.yaml:
```
enabled: true
from: bob@bobrockefeller.com
from_name: Bob Rockefeller
mailer:
  engine: smtp
  smtp:
    server: minutemen.reclaimhosting.com
    port: 465
    encryption: SSL
    user: 'XXXXX'
    password: 'XXXXX'
  sendmail:
    bin: '/usr/sbin/sendmail'
content_type: text/html
debug: false
```

My form blueprint:
```
form:
  name: contact-form
  method: POST

  fields:
    - name: name
      label: Name:
      autofocus: on
      autocomplete: on
      type: text
      validate:
        required: true
      outerclasses: contact-form-name

    - name: email
      label: Email:
      type: email
      validate:
        required: true
      outerclasses: contact-form-email

    - name: message
      label: Message:
      type: textarea
      validate:
        required: true
      outerclasses: contact-form-body
      
    - name: honeypot
      type: honeypot
      
  buttons:
    - type: submit
      value: Submit
      classes: contact-form-button
    - type: reset
      value: Reset
      classes: contact-form-button
      
  process:
    - email:
      subject: Contact from BR.com
      to: photos@bobrockefeller.com
      to_name: Bob Rockefeller
      from: "{{form.value.email|e}}"
      from_name: "{{form.value.name|e}}"
      body: "{{form.value.message|e}}"
```

When the form processes and attempts to send the email, I get this error:

```
Server Error
Sorry, something went terribly wrong!

0 - Argument 1 passed to Grav\Plugin\EmailPlugin::buildMessage() must be of the type array, null given, called in /Users/bob/Dropbox/SyncedSites/vhosts/www.br.dev/user/plugins/email/email.php on line 74
```

So I have something screwed up somewhere. But what?
