### ISSUE TITLE
e-mail not send.

### ISSUE THREAD

**Issue by andyberkoff** [getgrav/grav-plugin-email#53]
Hey.
I'm new to GRAV. I have a problem. Do not send letters from the site. I use the contact form. Palgin set up as specified in the documentation. I checked the sending of mail from the server where the site is hosted - everything is sent.
I check the plugin using CLI: bin / plugin email test-email -t andy_matveev@mail.ru
I receive an output in the console: 

Current Configuration:

```
array:8 [
  "enabled" => true
  "from" => "andy_matveev@mail.ru"
  "from_name" => null
  "to" => "andy_matveev@mail.ru"
  "to_name" => null
  "mailer" => array:3 [
    "engine" => "mail"
    "smtp" => array:5 [
      "server" => "localhost"
      "port" => 25
      "encryption" => "none"
      "user" => ""
      "password" => ""
    ]
    "sendmail" => array:1 [
      "bin" => "/usr/sbin/sendmail"
    ]
  ]
  "content_type" => "text/html"
  "debug" => false
]
```

Message sent successfully!

The message is saved in the user / data / my-niceform folder
But it does not come to my mailbox!
If I send a message, use the server's command line
sendmail -v andy_matveev@mail.ru
Then a message appears in my mailbox. Thus, using the contact form, I can not send a message. The same happens if I use a form to render a message with an attached file. The file is not attached and the message is not sent. Here is the file with the form:

```
title: Связь
action: '@self'
cache_enable: false
form:
    name: my-nice-form
    fields:
        -
            name: name
            label: Имя
            placeholder: 'ваше имя'
            autofocus: 'on'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            label: Е-майл
            placeholder: 'ваш е-майл'
            type: text
            validate:
                rule: email
                required: true
        -
            name: phone
            label: Телефон
            placeholder: 'Номер телефона'
            type: text
            validate:
                required: true
        -
            name: message
            label: Сообщение
            size: long
            placeholder: сообщение
            type: textarea
            validate:
                required: true
        -
            name: my-file
            label: 'Добавить файл'
            type: file
            multiple: true
            description: 'Перетащите файлы сюда'
            destination: 'user/data'
    buttons:
        -
            type: submit
            value: Submit
            classes: btn
        -
            type: reset
            value: Reset
            classes: btn
    process:
        -   email:
                from: "{{ form.value.email|e }}"
                to: "{{ config.plugins.email.to }}"
                subject: "Contact by {{ form.value.name|e }}"
                body: "{% include 'forms/data.html.twig' %}"
                attachments: 'my-file'
        -   save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %} {{ config.plugins.email.from }} {{ config.plugins.email.my-file }}'
        -   message: 'Thank you for your feedback!'
        -   display: thankyou
    reset: true
```
