### ISSUE TITLE
Form file upload does not work

### ISSUE THREAD

**Issue by piotrjozwiak** [getgrav/grav-plugin-email#58]
Hi guys!
I heve problem with attaching files to email message.
I have configured this fields:

```
form:
action: /contact
name: contact-form
fields:
…

    name: my-file
    label: 'Add a file'
    type: file
    multiple: false
    destination: user/data/files
    accept:
        - application/pdf
        - application/x-pdf
        - image/png
        - text/plain
buttons:
-
  type: submit
  value: 'Send Message’
  classes: 'btn btn-primary’
  process:
-
  email:
    from: ‘{{ config.plugins.email.from }}‘
    to: [’{{ config.plugins.email.to }}’]
    subject: '[Contact] {{ form.value.name|e }}'
    body: '{% include ‘‘forms/data.html.twig’’ %}'
    content_type: 'text/html’
    charset: 'UTF-8’
    attachments:
        - my-file
```
But still i receive messages without attachment.
Also ajax upload does not work and it looks like inactive button. I have to uncheck “display: none” in css properties.
Anybody have idea what is a problem?

I am testing this on localhost and also building by heroku on herokuapp.com
