### ISSUE TITLE
Multiple E-mail

### ISSUE THREAD

**Issue by ixlayer** [getgrav/grav-plugin-email#69]
Cannot sent email, when e-mail is set to multiple.
Config:
enabled: true
from: no-reply@example.com
from_name: no-reply
to:
  - test@example.com
  - test1@example.com
to_name: test
mailer:
  engine: smtp
  smtp:
    server: smtp.gmail.com
    port: 587
    encryption: tls
    user: no-reply@example.com
    password: password
  sendmail:
    bin: /usr/sbin/sendmail
content_type: text/html
debug: true

**Comment by rhukster** [comment]
Please paste your YAML snippet in a code block:

<img width="745" alt="grav-plugin-email 2017-10-31 15-20-24" src="https://user-images.githubusercontent.com/1084697/32249545-0a8597be-be4f-11e7-8d55-6000dcea9837.png">

I can't make any sense of the YAML without it

**Comment by ixlayer** [comment]
`enabled: true
from: no-reply@example.com
from_name: no-reply
to:
  - test@example.com
  - test1@example.com
to_name: test
mailer:
engine: smtp
smtp:
server: smtp.gmail.com
port: 587
encryption: tls
user: no-reply@example.com
password: password
sendmail:
bin: /usr/sbin/sendmail
content_type: text/html
debug: true`

**Comment by rhukster** [comment]
Looked at this? https://github.com/getgrav/grav-plugin-email/issues/59#issuecomment-327471648

**Comment by ixlayer** [comment]
```
enabled: true
from: no-reply@example.com
from_name: no-reply
to:
  - test@example.com
  - test1@example.com
to_name: test
mailer:
engine: smtp
smtp:
server: smtp.gmail.com
port: 587
encryption: tls
user: no-reply@example.com
password: password
sendmail:
bin: /usr/sbin/sendmail
content_type: text/html
debug: true
```
 ```
           email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.to }}', '{{ form.value.email }}']
                subject: '[Test] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
```
