### ISSUE TITLE
Critical error during the rendering of a template via Grav Admin Plugin

### ISSUE THREAD

**Issue by justinhartman** [getgrav/grav-plugin-email#82]
Hi Guys,

See some basic setup information below:

![admin-plugins](https://user-images.githubusercontent.com/717118/36574746-cee27ea6-184f-11e8-9734-8cab6c1bbada.png)

I was trying to access the Email plugin (v2.7.1) settings via the [Admin Panel v1.6.7][1] but when clicking on the Email link `/admin/plugins/email` I got to see this wonderful screen:

![admin-error](https://user-images.githubusercontent.com/717118/36574745-ce98b83e-184f-11e8-8377-5eb1b4e035d5.png)

I've [dumpped the error log file][2] for you guys and this is from the point of breaking. I'm not really sure why there's an array when trying to load a template but I hope that the info you have allows you to debug this properly.

My environment settings are as follows:
- Grav v1.3.10
- MacBook Pro (13-inch, Mid 2012)
- macOS 10.13.3
- Apache/2.4.29 (Unix)
- PHP Version 7.2.2
- Darwin macbookpro 17.4.0 
- Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 

[1]: https://github.com/getgrav/grav-plugin-admin
[2]: https://gist.github.com/justinhartman/89b00a2bc930242cfc00064a97ee67ad

**Comment by rhukster** [comment]
What does your `user/config/plugins/email.yaml` look like?

**Comment by justinhartman** [comment]
I've changed the email addresses in the yaml file below and removed my access details to sendgrid but the rest is as per my `email.yaml` file.
```yaml
enabled: true
from: enquiries@email.com
to:
  -
    mail: enquiries@email.com
    name: Website Enquiries
  -
    mail: email@gmail.com
    name: Justin Hartman
mailer:
  engine: smtp
  smtp:
    server: smtp.sendgrid.net
    port: 587
    encryption: tls
    user: 'OMMITTED'
    password: 'OMMITTED'
  sendmail:
    bin: '/usr/sbin/sendmail'
```

**Comment by justinhartman** [comment]
OK, it loads perfectly when I remove one of my two `to` email addresses like so:
```yaml
enabled: true
from: enquiries@email.com
to:
    mail: enquiries@email.com
    name: Website Enquiries
mailer:
  engine: smtp
  smtp:
    server: smtp.sendgrid.net
    port: 587
    encryption: tls
    user: 'OMMITTED'
    password: 'OMMITTED'
  sendmail:
    bin: '/usr/sbin/sendmail'
```
Does this mean that instead of having two email addresses in the `to` field I should use one in the `to` and the other in the `cc` field? Is it not able to accept two emails in the `to` field?
