### ISSUE TITLE
Issues with mailgun

### ISSUE THREAD

**Issue by avxkim** [getgrav/grav-plugin-email#88]
Info from README:

```
mailer:
  engine: smtp
  smtp:
    server: smtp.mailgun.org
    port: 587
    encryption: tls
    user: 'MAILGUN_EMAIL_ADDRESS'
    password: 'MAILGUN_EMAIL_PASSWORD'
```

But i've used mailgun in laravel, and it was using `domain` and `secret` fields. You didn't test yourself before posting that info?
